# -*- coding: utf-8 -*-
"""Convert_Img_>_CSV.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xwmZdYJ2n0N0YQr8UkgNVbULFs9OfGSu
"""

# Required Libraries
from os import listdir
from os.path import isfile, join
from pathlib import Path
import cv2
import argparse
import numpy as np
import csv
import os
#ข้อมูลที่ใช้จะเชื่อมต่อกับ Colab
from google.colab import drive
drive.mount('/content/drive')
from PIL import Image
import sys


def createFileList(myDir, format='.jpg'):
  fileList = []
  print(myDir)
  for root, dirs, files in os.walk(myDir, topdown=False):
      for name in files:
          if name.endswith(format):
              fullName = os.path.join(root, name)
              fileList.append(fullName)
  return fileList

# โหลดข้อมูลรูปภาพ
myFileList = createFileList('/content/drive/Shareddrives/Clarity_V-Car/Dataset/') # ตำแหน่งของข้อมูล

for file in myFileList:
    print(file)
    img_file = Image.open(file)
    # img_file.show()

    # get original image parameters...
    width, height = img_file.size
    format = img_file.format
    mode = img_file.mode

    # Make image Greyscale
    img_grey = img_file.convert('L')
    #img_grey.save('result.png')
    #img_grey.show()

    # Save Greyscale values
    value = np.asarray(img_grey.getdata(), dtype=np.int).reshape((img_grey.size[1], img_grey.size[0]))
    value = value.flatten()
    print(value)
    with open("img_pixels.csv", 'a') as f:
        writer = csv.writer(f)
        writer.writerow(value)
